pub mod scatter;
pub mod line;
pub mod bar;
pub mod histogram;
pub mod histogram2d;
pub mod boxplot;
pub mod violin;
pub mod pie;
pub mod series;
pub mod heatmap;
pub mod brick;
pub mod band;
pub mod waterfall;
pub mod strip;
pub mod volcano;
pub mod manhattan;
pub mod dotplot;
pub mod upset;
pub mod stacked_area;
pub mod candlestick;
pub mod contour;
pub mod chord;
pub mod sankey;
pub mod phylo;
pub mod synteny;
pub mod density;
pub mod ridgeline;
pub mod polar;
pub mod ternary;
pub mod forest;

pub mod legend;

// pub mod types;

pub use scatter::{ScatterPlot, MarkerShape};
pub use line::{LinePlot, LineStyle};
pub use bar::BarPlot;
pub use histogram::Histogram;
pub use histogram2d::Histogram2D;
pub use boxplot::{BoxPlot, BoxGroup};
pub use violin::{ViolinPlot, ViolinGroup};
pub use pie::{PiePlot, PieSlice, PieLabelPosition};
pub use series::{SeriesPlot, SeriesStyle};
pub use heatmap::{Heatmap, ColorMap};
pub use brick::BrickPlot;
pub use band::BandPlot;
pub use waterfall::{WaterfallPlot, WaterfallBar, WaterfallKind};
pub use strip::{StripPlot, StripGroup, StripStyle};
pub use volcano::{VolcanoPlot, VolcanoPoint, LabelStyle};
pub use manhattan::{ManhattanPlot, ManhattanPoint, ChromSpan, GenomeBuild};
pub use dotplot::{DotPlot, DotPoint};
pub use upset::{UpSetPlot, UpSetIntersection, UpSetSort};
pub use stacked_area::StackedAreaPlot;
pub use candlestick::{CandlestickPlot, CandleDataPoint};
pub use contour::ContourPlot;
pub use chord::ChordPlot;
pub use sankey::{SankeyPlot, SankeyNode, SankeyLink, SankeyLinkColor};
pub use phylo::{PhyloTree, PhyloNode, TreeOrientation, TreeBranchStyle};
pub use synteny::{SyntenyPlot, SyntenyBlock, SyntenySequence, Strand};
pub use density::DensityPlot;
pub use ridgeline::{RidgelinePlot, RidgelineGroup};
pub use polar::{PolarPlot, PolarSeries, PolarMode};
pub use ternary::{TernaryPlot, TernaryPoint};
pub use forest::{ForestPlot, ForestRow};

pub use legend::{Legend, LegendEntry, LegendShape, LegendPosition, LegendGroup};